name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mlflow-env
          python-version: "3.12"
          
      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run MLproject/

      - name: Save MLflow artifacts
        shell: bash -l {0}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git lfs install
          git lfs track "mlruns/**"

          git add .gitattributes
          git commit -m "Configure Git LFS" || true

          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true

          git push origin main
